/scan:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile

/camera/front/depth/image_raw:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile

/camera/front/camera_info:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile

/clock:
  history: keep_last
  depth: 1
  reliability: best_effort
  durability: volatile

/cmd_vel_nav:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: volatile

/cmd_vel_smoothed:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: volatile

/cmd_vel_sim:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: volatile

/collision_monitor_state:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: volatile

/tf_static:
  history: keep_last
  depth: 100
  reliability: reliable
  durability: transient_local
