#!/usr/bin/env python3
"""Generate the frozen fresh-seed Attempt27 static and dynamic scenarios."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "ros2_ws/src/robot_experiments/config"
BASE = {
    "static": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_static.yaml",
    "dynamic": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_dynamic.yaml",
}
SEEDS = {
    ("diagnostic", "static"): range(33201, 33207),
    ("diagnostic", "dynamic"): range(33251, 33257),
    ("smoke", "static"): range(33301, 33307),
    ("smoke", "dynamic"): range(33351, 33357),
    ("calibration", "static"): range(33401, 33411),
    ("calibration", "dynamic"): range(33501, 33511),
    ("heldout", "static"): range(33601, 33631),
    ("heldout", "dynamic"): range(33701, 33741),
    ("formal", "static"): range(33801, 33831),
    ("formal", "dynamic"): range(33901, 33941),
}


def main() -> None:
    for (stage, mode), seed_range in SEEDS.items():
        document = yaml.safe_load(BASE[mode].read_text(encoding="utf-8"))
        scenario = deepcopy(document["scenario"])
        scenario_id = f"isaac_kujiale_dataset_v3_attempt27_{stage}_{mode}"
        templates = scenario["runs"]["matrix"]
        rows = []
        for index, seed in enumerate(seed_range):
            template = templates[index % len(templates)]
            rows.append({
                "seed": seed,
                "case_id": template["case_id"],
                "variant_id": template["variant_id"],
                "condition_id": f"attempt27_{stage}_{mode}",
            })
        scenario["id"] = scenario_id
        scenario["runs"]["matrix"] = rows
        output = CONFIG / f"{scenario_id}.yaml"
        output.write_text(
            "# Generated by scripts/generate_attempt27_a18_scenarios.py.\n"
            + yaml.safe_dump(
                {"schema_version": document["schema_version"], "scenario": scenario},
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        print(output)


if __name__ == "__main__":
    main()
