#!/usr/bin/env python3
"""Generate one-route static/dynamic scenarios for the fast fusion smoke."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml


def _scenario(source: Path, *, dynamic: bool) -> dict:
    payload = yaml.safe_load(source.read_text(encoding="utf-8"))
    result = deepcopy(payload)
    scenario = result["scenario"]
    mode = "dynamic" if dynamic else "static"
    scenario["id"] = f"isaac_kujiale_dataset_v2_smoke_{mode}"
    scenario["runs"]["matrix"] = [
        {
            "seed": 15101 if dynamic else 15001,
            "case_id": "full_route_three_stage" if dynamic else "static",
            "variant_id": "v1" if dynamic else "dataset_v2_smoke_v1",
            "condition_id": f"{mode}_baseline",
            "appearance_profile_id": "baseline",
        }
    ]
    return result


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    config = root / "ros2_ws/src/robot_experiments/config"
    pairs = (
        ("static", "kujiale_stage2_2_stage_b_r1_static.yaml", False),
        ("dynamic", "kujiale_stage2_2_stage_b_r1_dynamic.yaml", True),
    )
    for mode, source_name, dynamic in pairs:
        output = config / f"isaac_kujiale_dataset_v2_smoke_{mode}.yaml"
        payload = _scenario(config / source_name, dynamic=dynamic)
        output.write_text(
            "# Generated by scripts/generate_bionav_fast_smoke_scenarios.py.\n"
            "# Engineering smoke only; never use as formal Gate evidence.\n"
            + yaml.safe_dump(payload, sort_keys=False),
            encoding="utf-8",
        )
        print(output)


if __name__ == "__main__":
    main()
