#!/usr/bin/env python3
"""Generate the explicit Attempt-26 preexecution and development scenarios."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "ros2_ws/src/robot_experiments/config"
BASE = {
    "static": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_static.yaml",
    "dynamic": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_dynamic.yaml",
}
SEEDS = {
    ("preexecution", "static"): range(32651, 32660),
    ("diagnostic", "static"): range(32660, 32684),
    ("smoke", "static"): range(32726, 32732),
    ("smoke", "dynamic"): range(32775, 32781),
    ("calibration", "static"): range(32811, 32821),
    ("calibration", "dynamic"): range(32917, 32927),
    ("heldout", "static"): range(33001, 33031),
    ("heldout", "dynamic"): range(33101, 33141),
}


def main() -> None:
    for (stage, profile), seed_range in SEEDS.items():
        document = yaml.safe_load(BASE[profile].read_text(encoding="utf-8"))
        scenario = deepcopy(document["scenario"])
        scenario_id = f"isaac_kujiale_dataset_v3_attempt26_{stage}_{profile}"
        condition_id = f"attempt26_{stage}_{profile}"
        template_rows = scenario["runs"]["matrix"]
        rows = []
        for index, seed in enumerate(seed_range):
            template = template_rows[index % len(template_rows)]
            rows.append({
                "seed": seed,
                "case_id": template["case_id"],
                "variant_id": template["variant_id"],
                "condition_id": condition_id,
            })
        scenario["id"] = scenario_id
        scenario["runs"]["matrix"] = rows
        output = CONFIG / f"{scenario_id}.yaml"
        output.write_text(
            "# Generated by scripts/generate_attempt26_a17_scenarios.py.\n"
            + yaml.safe_dump(
                {"schema_version": document["schema_version"], "scenario": scenario},
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        print(output)


if __name__ == "__main__":
    main()
