#!/usr/bin/env python3
"""Generate frozen fresh-seed Attempt28 static and dynamic scenarios."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "ros2_ws/src/robot_experiments/config"
BASE = {
    "static": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_static.yaml",
    "dynamic": CONFIG / "isaac_kujiale_dataset_v3_attempt23_global_shadow_dynamic.yaml",
}
SEEDS = {
    # The first static Engineering pool was consumed by attributable repair
    # iterations.  Keep qualification ranges untouched and add a disjoint,
    # non-qualification reserve instead of reusing evidence or borrowing a
    # Diagnostic/Smoke/Calibration/Heldout/Formal seed.
    ("engineering", "static"): (
        *range(34001, 34041), *range(34601, 34641)
    ),
    ("engineering", "dynamic"): range(34051, 34091),
    ("diagnostic", "static"): range(34101, 34107),
    ("diagnostic", "dynamic"): range(34151, 34157),
    ("smoke", "static"): range(34201, 34207),
    ("smoke", "dynamic"): range(34251, 34257),
    ("calibration", "static"): range(34301, 34311),
    ("calibration", "dynamic"): range(34351, 34361),
    ("heldout", "static"): range(34401, 34431),
    ("heldout", "dynamic"): range(34451, 34491),
    ("formal", "static"): range(34501, 34531),
    ("formal", "dynamic"): range(34551, 34591),
}


def main() -> None:
    for (stage, mode), seed_range in SEEDS.items():
        document = yaml.safe_load(BASE[mode].read_text(encoding="utf-8"))
        scenario = deepcopy(document["scenario"])
        scenario_id = f"isaac_kujiale_dataset_v3_attempt28_{stage}_{mode}"
        templates = scenario["runs"]["matrix"]
        scenario["id"] = scenario_id
        scenario["runs"]["matrix"] = [
            {
                "seed": seed,
                "case_id": templates[index % len(templates)]["case_id"],
                "variant_id": templates[index % len(templates)]["variant_id"],
                "condition_id": f"attempt28_{stage}_{mode}",
            }
            for index, seed in enumerate(seed_range)
        ]
        output = CONFIG / f"{scenario_id}.yaml"
        output.write_text(
            "# Generated by scripts/generate_attempt28_a19_scenarios.py.\n"
            + yaml.safe_dump(
                {"schema_version": document["schema_version"], "scenario": scenario},
                sort_keys=False,
            ),
            encoding="utf-8",
        )
        print(output)


if __name__ == "__main__":
    main()
