#!/usr/bin/env python3
"""Generate the optional BioNav profile from the validated dynamic overlay."""

from __future__ import annotations

import argparse
from copy import deepcopy
from pathlib import Path

import yaml

WAREHOUSE_NEW_OCCUPANCY_VERSION = (
    "1a45950d7b1854596231549e853bf7051ad22b1a53a428d31ba41c6b055685cf"
)


def build_profile(dynamic_profile: Path) -> dict:
    payload = yaml.safe_load(dynamic_profile.read_text(encoding="utf-8"))
    result = deepcopy(payload)
    global_parameters = result["global_costmap"]["global_costmap"]["ros__parameters"]
    plugins = list(global_parameters["plugins"])
    if "cognitive_risk_layer" not in plugins:
        plugins.insert(plugins.index("inflation_layer"), "cognitive_risk_layer")
    global_parameters["plugins"] = plugins
    global_parameters["cognitive_risk_layer"] = {
        "plugin": "bio_nav_fusion::CognitiveRiskLayer",
        "enabled": True,
        "prior_topic": "/bio_nav/module2/planning_prior",
        "reset_topic": "/simulation/reset_event",
        "max_message_age_s": 0.75,
        "minimum_reliability": 0.2,
        "maximum_cost": 80,
        # This is the hash published by the Integration bridge for the
        # warehouse_new occupancy bundle, not the human-facing map alias.
        "expected_map_version": WAREHOUSE_NEW_OCCUPANCY_VERSION,
        "expected_risk_model_sha256": "",
        "expected_qualification_sha256": "",
        "initial_reset_epoch": 0,
    }
    result["planner_server"] = {
        "ros__parameters": {
            "planner_plugins": ["GridBased"],
            "GridBased": {
                "plugin": "bio_nav_fusion::BioNavGridBased",
                "prior_service": "/bio_nav/get_goal_planning_prior",
                "planning_prior_topic": "/bio_nav/module2/planning_prior",
                "service_timeout_ms": 100,
                "allow_unknown": True,
                "expected_module3_map_sha256": "",
                "expected_qualification_sha256": "",
            },
            # The wrapper calls this stock plugin directly whenever cognition
            # is absent, stale, invalid, or cannot find a path.
            "GridBased_fallback": {
                "tolerance": 0.10,
                "downsample_costmap": False,
                "allow_unknown": True,
                "max_iterations": 1000000,
                "max_on_approach_iterations": 1000,
                "max_planning_time": 2.0,
                "cost_travel_multiplier": 1.2,
                "use_final_approach_orientation": False,
                "smoother": {
                    "max_iterations": 1000,
                    "w_smooth": 0.30,
                    "w_data": 0.20,
                    "tolerance": 1.0e-10,
                    "do_refinement": True,
                },
            },
        }
    }
    return result


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dynamic-profile",
        type=Path,
        default=root
        / "ros2_ws/src/robot_navigation/config/nav2_dynamic_avoidance.yaml",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root
        / "ros2_ws/src/robot_navigation/config/nav2_bio_nav_tiebreak_risk.yaml",
    )
    args = parser.parse_args()
    payload = build_profile(args.dynamic_profile.resolve())
    target = args.output.resolve()
    target.write_text(
        "# Generated by scripts/generate_bionav_fusion_profile.py.\n"
        "# Optional engineering profile; stable/dynamic_avoidance remain defaults.\n"
        + yaml.safe_dump(payload, sort_keys=False),
        encoding="utf-8",
    )
    print(target)


if __name__ == "__main__":
    main()
